### ISSUE TITLE
Unable to install Nvidia drivers 173_14 on dedicab.

### ISSUE THREAD

**Issue by Soliaonline** [concubidated/itgpro2#15]
I actually have 2 dedicabs.  One is  Andamiro and the other is not.

The Andamiro machine has an graphics card and the other does not.

Andamiro also only has a 40 GB harddrive while the other has a 80 GB both are Maxtor.

I am attempting to install this on the non-Andamiro cabinet.  I am quite familiar with Linux I have used all ubuntu LTS since 08.   The instructions of a dedicab say to use 12.04.01 Server.  After installing it and getting it all to boot I try to run this and the Nvidia was first failing on dependence; binutils, gcc and make.    

Now it fails on https://imgur.com/a/OPelivm

'kernel-source' and/or 'kernel-devel'   apt-get install finds neither of those.  I am hoping you can get me going.

**Andamiro** Hardware
https://imgur.com/a/ftn6X0l

**Non-Andamiro**  Hardware
https://imgur.com/a/oOVD9m2

I tried ignoring the nvidia errors and finished the entire install, but start itg does not do anything. (stop itg) says process not found.  I assume it failed to start and says nothing.

**Comment by tj28** [comment]
This was not tested on an iGPU yet to my knowledge. My suggestion would be to buy a GeForce FX 5200 and try again to be honest. It will perform better, works on original software, and they're basically free at this point

Would also make sure you're using kernel 3.20 (you can check this with `uname -r`)
If you can get an internet connection on your cab:
`sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list`
`sudo apt-get update`
`sudo apt-get source linux-image-3.20.X-XX-generic`


Where ".X-XX" is your exact kernel version number (again, you can check this with `uname -r`)

Hope this helps

Edit: Just realized you already have a FX5200...Try plugging it into your non-andamiro and try again just to see if that's the fix

**Comment by Soliaonline** [comment]
Since the other cab has an FX 6200, am I able to just use that?

Are any of the other video cards PCI-E?

**Comment by Soliaonline** [comment]
I am not familiar with updating the kernel like this, so I tried  it a few different ways and all resulted in failure.  

https://imgur.com/a/ZdY4zaQ

The second photo is after a restart seeing if it would breed different results.   I took a picture of the sed command, maybe there is an error in it  (Using the up arrow after the apt-get source failed)?

12.04.1 default kernel is 3.2.0-29-generic-pac

**Comment by tj28** [comment]
It's `pae` not `pac`. Please try:
`apt-get source linux-image-3.2.0-29-generic-pae`
`apt-get install linux-headers-3.2.0-29-generic-pae`
and run the installer again.

Just FYI FX 5200 not 6200. Yes you can swap the graphics card (assuming both are PCI-E or AGP) into your non-andamiro if you really get stuck getting this iGPU working.

**Comment by Soliaonline** [comment]
I am sorry, I am a bit confused there.  I thought you wanted me to install linux-image-3.20?

I did a lot of work on it yesterday.  andamiro machine has 256 MB Ram while the andamiro has 2gb of ram.  

Is there a reason I need to use 12.04 for it instead of 14.04?

----

Update

I have tried everything suggested and it just keeps saying unable to find a source package.

https://imgur.com/a/AA9dr4y

I am sure I am doing something wrong if you could please point me in the right direction.


----

I took another drive and installed 14.04.  This time everything worked correctly.  I can do start itg it goes to the blue screen like on the normal arcade startup, flickers and goes back to terminal, trys again and then fails again.  I am thinking maybe the NVIDIA drivers (which did install without error) may be the cause this time.  How would I find out what Nvidia driver I need for the onboard video card?  Based on the markings on the Chip it is an nForce 410 NVIDIA chip.

**Comment by tj28** [comment]
Sorry I meant 3.2.0 not 3.20. Was going off memory. I haven't had to deal with this since I redid may cab like 4 years ago.

Please try running the commands exactly as stated. I dug around a little bit more and just the `linux-headers` command might do the trick (based on some other people with the same error message)

The reason I suggest 12.04 is because I couldn't get nvidia 174 driver to work on newer kernels. Same issue you had. Drivers install but itg doesn't load. Forgot exactly which kernel it stopped working on, want to say like 3.13

Yes, all of my knowledge is getting a FX5200 dGPU working, I would imagine the iGPU would be the same exact process but it may not be.

**Comment by Soliaonline** [comment]
OKay, so the iGPU is a NVIDIA GeForce 6100 GX   (When I tried installing 331 drive it told me what it was)


If you look at the photos I did try 

apt-get source linux-image-3.20-generic-pae
apt-get source linux-headers-3.20-generic

and both spit back that "unable to find a source package."

I ordered a 210 but no telling when it will get here.  I can go back to the other harddrive with 12.04.  Would you please help me get that kernel upgrade command working.

**Comment by tj28** [comment]
> OKay, so the iGPU is a NVIDIA GeForce 6100 GX (When I tried installing 331 drive it told me what it was)
> 
> If you look at the photos I did try
> 
> apt-get source linux-image-3.20-generic-pae
> apt-get source linux-headers-3.20-generic
> 
> and both spit back that "unable to find a source package."
> 
> I ordered a 210 but no telling when it will get here. I can go back to the other harddrive with 12.04. Would you please help me get that kernel upgrade command working.

Ah interesting so the iGPU is a 6 series. That means you can use the nvidia 304.137 driver but the one included in the script (173.14) also supports the 6 series and should work fine. 

In your screenshot you did `linux-image-3.20.3.2.0.29-generic-pae` and `linux-image-3.20-generic` but that's not what I wrote above, please read carefully!!

**Comment by Soliaonline** [comment]
I have tried many things by now, I know I didn't include all the things I tried because I didn't want to harass you.

I found...
https://www.devmanuals.net/install/ubuntu/ubuntu-12-04-lts-precise-pangolin/install-linux-image-3.11.0-26-generic.html

did that and it actually works with the iGPU.

**Comment by tj28** [comment]
Huh interesting. Perhaps 3.2.0 is too old for the 3xx drivers. Glad you figured it out!

**Comment by Soliaonline** [comment]
Thank you very much for taking the time to help me at all.  If this helps, I do have an awesome light replacement for the arcade, that is 1.60 cents per pad square.    They replace the entire wooden piece, and florescent bulb.

https://www.superbrightleds.com/moreinfo/led-module-strings/single-color-led-module-square-constant-current-sign-module-w-4-smd-leds/980/2393/

**Comment by Soliaonline** [comment]
How do I add custom songs?  I made a folder called custom and I put the Songs/Cache in there but after the machine boots nothing.  Do I need to edit anything else for it to read the custom folder?  Funny enough I wrote a guide on r21freak on how to do all of this in 2009.

Cached version since r21 is down.

http://cc.bingj.com/cache.aspx?q=Adding+songs+to+ITG+machine&d=4967466519429662&mkt=en-US&setlang=en-US&w=d2DJKFkd8DTS8RZNfwrYlVj0FIGqi5ds

---

nevermind, I look at Static.ini inside hda3.  Thank you.

**Comment by tj28** [comment]
It's been forever but a good place to start;
Make sure your file structure looks something like this
/itgdata/itgcustom/Songs/pack_name/pack_songs

I think your Static.ini should have something like
AdditionalSongFolders=/itgdata/itgcustom

Lastly you don't need to bring over the cache in oitg it should auto-generate upon boot. This probably doesn't matter but you can also try letting it cache on its own

**Comment by Soliaonline** [comment]
I have 1 issue on the dedicab, not sure if its something you all can/would even fix.  The Player 1 and Player 2 are reversed so far as the USBs in the front go.  Player 2 -> 1 and vis versa.

Edit:
Is there anyway to edit the default speed mods without adding a theme?

**Comment by tj28** [comment]
I think by default;


`# With USB hub attached to any port, Player 1 in the leftmost port (Port 0)`
` # and Player 2 in the rightmost port (Port 3)`
MemoryCardUsbBusP1=-1
MemoryCardUsbBusP2=-1
MemoryCardUsbLevelP1=-1
MemoryCardUsbLevelP2=-1
MemoryCardUsbPortP1=1
MemoryCardUsbPortP2=4


So you could try
MemoryCardUsbPortP1=4
MemoryCardUsbPortP2=1


User profiles (which store your last used speed mod iirc) are stored on your usb. I think you can force use a profile via Static.ini as well if you really wanted to

**Comment by Soliaonline** [comment]
I just wanted to add 3.5 and 4.5 to the machine.  Thank you very much for your help.  I will give the port switch a try tomorrow and see how that goes.

**Comment by Soliaonline** [comment]
(Yesterday I was in court for a speeding ticket, cop said I was doing way over what I was)

Today, I was able to test this.  I am able to edit all of the other files in SDA3 and have it stick.  If I edit Static.ini it as soon as I start up the arcade the file is changed back to the default.

In my case the default is 

MemoryCardUsbPortP1=4
MemoryCardUsbPortP2=1

And you're completely right it does need to be:
MemoryCardUsbPortP1=1
MemoryCardUsbPortP2=4

I have tried editing the file and running "sync" afterwards, but as soon as the arcade starts up the file is back to the default file.  (I have also tried uncommenting the line that tells it to use SIMPLY LOVE theme and that is again commented out.)

**Comment by tj28** [comment]
To add speed mods I believe you'll have to modify the theme there should be tutorials of how to do that out on the interwebs.

Do certain game files get unpacked every start-up? Can't remember. Anyhow a shoe-horn solution to your problem might be  `chmod 444 Static.ini` (will set file as read-only, `chmod 777` to reverse)

**Comment by Soliaonline** [comment]
lol, I made the tutorial to do it on r21freak, so yeah I know how to mod the theme, I didn't know if it was possible otherway.  

I'll set it to 444, thanks.  I do seriously work with Linux everyday for work, but I have never done kernel updates or anything with installing sata drives.  I have the original harddrive doing a DD right now.  I would like ultimately to keep it in tact in case I ever sell one of the machines.


Other note, I have a DDR Extreme, is there anyway without the ITG upgrade kit to use this dist to turn it into an open ITG?

**Comment by tj28** [comment]
> lol, I made the tutorial to do it on r21freak, so yeah I know how to mod the theme, I didn't know if it was possible otherway.
> 
> I'll set it to 444, thanks. I do seriously work with Linux everyday for work, but I have never done kernel updates or anything with installing sata drives. I have the original harddrive doing a DD right now. I would like ultimately to keep it in tact in case I ever sell one of the machines.
> 
> Other note, I have a DDR Extreme, is there anyway without the ITG upgrade kit to use this dist to turn it into an open ITG?

Yes you need a JPAC or an ITGIO to basically "convert" the JAMMA signal to USB & VGA

**Comment by Soliaonline** [comment]
God damnit... I had 2 JPACs and sold both on eBay about 2 months ago.  I think I still have the Ultramark CD.

Any guides online for it?  I'll order another and do it.  It an Extreme was my first machine, honestly I probably need to put a new monitory/replacement in it.

**Comment by tj28** [comment]
Never used a jpac. Probably though

**Comment by Soliaonline** [comment]
Guide, if anyone in the future reads this and wants help.
https://rhythmarcade.com/wiki/custom_setups/input/ddr_to_oitgstepmania_conversion

Do you happen to know a good place to get replacement pad screws, Allen wrench kind?
