### ISSUE TITLE
Horizontal refresh not correct

### ISSUE THREAD

**Issue by tj28** [concubidated/itgpro2#4]
XF86Config-kit has the following two lines commented out:
    VertRefresh 60
    HorizSync   15.75   

Causing the screenshot attached.
![dsc_0189](https://cloud.githubusercontent.com/assets/6042288/15048259/cbb03750-12b6-11e6-8fa1-00e0d1b4cee3.JPG)

**Comment by concubidated** [comment]
So, this is interesting, I run a kit, and have to comment those lines out with the newer drivers. I will play with it later, but took out the comments for now. This is with 173.14 you are seeing this?

**Comment by tj28** [comment]
Yes.
Do you need HorizSync 15.75 with the original OS? That'll let us know if it's a driver or a monitor/xorg issue.

**Comment by concubidated** [comment]
With the original driver you do need it. I took it out when I upgraded to a newer driver. I'll put it on my cab with some newer drivers and see how it reacts.

**Comment by concubidated** [comment]
Updated the Xorg to uncomment these values out, not sure how they get that way in the first place...
