### ISSUE TITLE
Unable to add songs 

### ISSUE THREAD

**Issue by dj505** [concubidated/itgpro2#5]
I don't know if this is an issue with the program or I'm not looking in the correct directory, but I'm unable to add songs. Assuming songs are added under the UserPacks folder, the folder is read only except for root and any added files don't show up.

**Comment by tj28** [comment]
You're not looking in the correct directory. Songs should be placed like this: /itgdata/itgcustom/Songs/PackName/SongName/SongName.sm

The second folder is either "custom" or "itgcustom", I can't remember

**Comment by concubidated** [comment]
I will add some more instructions to the readme for adding songs. For Future reference,

The file /stats/patch/Static-default.ini shows the AdditionalFolders=/itgdata/itgcustom/

This means you need to create a Songs folder in /itgdata/itgcustom/
