### ISSUE TITLE
Custom Songs Won't Load

### ISSUE THREAD

**Issue by dj505** [concubidated/itgpro2#6]
Placed custom songs in /itgdata/itgcustom/Songs, but song folders do not appear on the in-game song select wheel.
Note: I'm not placing individual songs in the /Songs foder, I'm placing the packs they belong to with the songs in those folders.
(Path: /itgdata/itgcustom/Songs/pack_name/pack_songs)
Another note: SIMPLY LOVE does not load nor does it appear in the themes menu.

**Comment by concubidated** [comment]
What does your Static.ini look like in _/stats/patch/Static-default.ini_

Also, what can you include the log when you start up itg? You can enable logging by adding 

`LogToDisk=1` in _/stats/patch/Static-default.ini_

**Comment by dj505** [comment]
My /stats/patch/Static-default.ini had the additional songs folder set to /itgdata/itgcustom/,  so it should have loaded. Apparently the issue was with my hardware and not the software, and I was too quick to open an issue under the assumption that it was a glitch. The partitions seemed to be set up wrong through the installer, but only because of an issue with my hard drive having some issues with partitioning and old hardware not being able to handle 3 terabytes properly. Sorry to bother you! :P
